"""migration

Revision ID: bfc3f64c3d94
Revises: e1c64993f258
Create Date: 2022-10-26 14:00:28.734995+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc3f64c3d94'
down_revision = 'e1c64993f258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visits', 'weight_out',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='app')
    op.alter_column('visits', 'checked_out',
               existing_type=sa.DATETIME(),
               nullable=True,
               schema='app')
    op.alter_column('visits', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visits', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='app')
    op.alter_column('visits', 'checked_out',
               existing_type=sa.DATETIME(),
               nullable=False,
               schema='app')
    op.alter_column('visits', 'weight_out',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='app')
    # ### end Alembic commands ###
