"""migration

Revision ID: 478da444ca05
Revises: da7afee5dc25
Create Date: 2022-11-02 09:14:56.639778+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478da444ca05'
down_revision = 'da7afee5dc25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_groups', schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_groups',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50, collation='Cyrillic_General_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_user_groups'),
    schema='app'
    )
    # ### end Alembic commands ###
