"""migration

Revision ID: 891b3f9917fc
Revises: bd196d4d73f8
Create Date: 2022-10-18 09:06:36.550370+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891b3f9917fc'
down_revision = 'bd196d4d73f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copy_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('permit_id', sa.Integer(), nullable=True),
    sa.Column('polygon_id', sa.Integer(), nullable=False),
    sa.Column('weighted_in', sa.Integer(), nullable=False),
    sa.Column('weighted_out', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('delete_reason', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['app.polygon.id'], name=op.f('fk_copy_visits_destination_id_polygon'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['driver_id'], ['app.users.id'], name=op.f('fk_copy_visits_driver_id_users'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['permit_id'], ['app.permits.id'], name=op.f('fk_copy_visits_permit_id_permits'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['polygon_id'], ['app.polygon.id'], name=op.f('fk_copy_visits_polygon_id_polygon'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['visit_id'], ['app.visits.id'], name=op.f('fk_copy_visits_visit_id_visits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_copy_visits')),
    schema='app'
    )
    op.drop_table('tonar_visits', schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tonar_visits',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('visit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weighted_out', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('destination_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['app.polygon.id'], name='fk_tonar_visits_destination_id_polygon'),
    sa.ForeignKeyConstraint(['driver_id'], ['app.users.id'], name='fk_tonar_visits_driver_id_users'),
    sa.ForeignKeyConstraint(['visit_id'], ['app.visits.id'], name='fk_tonar_visits_visit_id_visits', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_tonar_visits'),
    schema='app'
    )
    op.drop_table('copy_visits', schema='app')
    # ### end Alembic commands ###
