"""migration

Revision ID: da7afee5dc25
Revises: bfc3f64c3d94
Create Date: 2022-10-27 09:19:15.516803+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da7afee5dc25'
down_revision = 'bfc3f64c3d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('copy_visits', 'weight_out',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='app')
    op.alter_column('copy_visits', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('copy_visits', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='app')
    op.alter_column('copy_visits', 'weight_out',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='app')
    # ### end Alembic commands ###
