"""migration

Revision ID: bd196d4d73f8
Revises: d5fce235c246
Create Date: 2022-10-06 05:52:17.577710+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd196d4d73f8'
down_revision = 'd5fce235c246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_models')),
    schema='app'
    )
    op.add_column('vehicles', sa.Column('model_id', sa.Integer(), nullable=False), schema='app')
    op.create_foreign_key(op.f('fk_vehicles_model_id_vehicle_models'), 'vehicles', 'vehicle_models', ['model_id'], ['id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    op.drop_column('vehicles', 'name', schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('name', sa.VARCHAR(length=250, collation='Cyrillic_General_CI_AS'), autoincrement=False, nullable=False), schema='app')
    op.drop_constraint(op.f('fk_vehicles_model_id_vehicle_models'), 'vehicles', schema='app', type_='foreignkey')
    op.drop_column('vehicles', 'model_id', schema='app')
    op.drop_table('vehicle_models', schema='app')
    # ### end Alembic commands ###
