"""migration

Revision ID: 0ff295b04a82
Revises: 1c62dc99f0d4
Create Date: 2022-12-07 15:40:25.435477+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0ff295b04a82'
down_revision = '1c62dc99f0d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'contragent_id',
                    existing_type=sa.INTEGER(),
                    nullable=True,
                    schema='app')
    op.alter_column('users', 'user_position',
                    existing_type=sa.VARCHAR(length=250),
                    nullable=True,
                    schema='app')
    op.create_index(op.f('ix_app_users_phone_number'), 'users',
                    ['phone_number'], unique=False, schema='app')
    op.drop_column('users', 'login', schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',
                  sa.Column('login', sa.VARCHAR(length=10), autoincrement=False,
                            nullable=False), schema='app')
    op.drop_index(op.f('ix_app_users_phone_number'), table_name='users',
                  schema='app')
    op.alter_column('users', 'user_position',
                    existing_type=sa.VARCHAR(length=250),
                    nullable=False,
                    schema='app')
    op.alter_column('users', 'contragent_id',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    schema='app')
    # ### end Alembic commands ###
