"""migration

Revision ID: fb4e8b38665b
Revises: 0ff295b04a82
Create Date: 2022-12-07 16:06:56.236114+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fb4e8b38665b'
down_revision = '0ff295b04a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password', schema='app')
    op.add_column('users',
                  sa.Column('password', sa.LargeBinary(), nullable=False),
                  schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password', schema='app')
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=12),
                                     autoincrement=False, nullable=False),
                  schema='app')
    # ### end Alembic commands ###
