"""migration

Revision ID: b7bf8aaded25
Revises: fb4e8b38665b
Create Date: 2022-12-07 16:41:16.984642+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b7bf8aaded25'
down_revision = 'fb4e8b38665b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_app_users_phone_number', table_name='users', schema='app')
    op.drop_column('users', 'phone_number', schema='app')
    op.add_column('users',
                  sa.Column('phone_number', sa.BigInteger(), nullable=True),
                  schema='app')
    op.create_index(op.f('ix_app_users_phone_number'), 'users',
                    ['phone_number'], unique=True, schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_users_phone_number'), table_name='users',
                  schema='app')
    op.drop_column('users', 'phone_number', schema='app')
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(length=15),
                                     autoincrement=False, nullable=True),
                  schema='app')
    op.create_index('ix_app_users_phone_number', 'users', ['phone_number'],
                    unique=False, schema='app')
    # ### end Alembic commands ###
