"""migration

Revision ID: 146064cc58b8
Revises: 0fcba3a5c0b9
Create Date: 2023-08-06 08:48:07.106205+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '146064cc58b8'
down_revision = '0fcba3a5c0b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'service_contract_visits',
        'invoice_num',
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_comment='Номер накладной',
        schema='app',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'service_contract_visits',
        'invoice_num',
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_comment='Номер накладной',
        schema='app',
    )
    # ### end Alembic commands ###
