"""migration

Revision ID: 3b76fc1c2230
Revises: a1c0d749d5c2
Create Date: 2023-08-05 17:31:20.197247+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3b76fc1c2230'
down_revision = 'a1c0d749d5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'executor_storage_areas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'polygon_id',
            sa.Integer(),
            nullable=False,
            comment='ИД полигона',
        ),
        sa.Column(
            'contract_id',
            sa.Integer(),
            nullable=False,
            comment='ИД договора',
        ),
        sa.ForeignKeyConstraint(
            ['contract_id'],
            ['app.service_contracts.id'],
            name=op.f(
                'fk_executor_storage_areas_contract_id_service_contracts'),
        ),
        sa.ForeignKeyConstraint(
            ['polygon_id'],
            ['app.polygons.id'],
            name=op.f('fk_executor_storage_areas_polygon_id_polygons'),
        ),
        sa.PrimaryKeyConstraint(
            'id',
            name=op.f('pk_executor_storage_areas'),
        ),
        schema='app',
        comment='Площадки накопления Исполнителя по договору на оказание услуг.'
    )
    op.alter_column(
        'service_contract_visits',
        'contract_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_comment='ИД договора',
        schema='app',
    )
    op.alter_column(
        'service_contract_visits',
        'invoice_num',
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_comment='Номер накладной',
        schema='app',
    )
    op.add_column(
        'service_contracts',
        sa.Column(
            'tariff',
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment='Тариф, руб./тонн',
        ),
        schema='app',
    )
    op.add_column(
        'service_contracts',
        sa.Column(
            'total_cost',
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment='Стоимость договора',
        ),
        schema='app',
    )
    op.add_column(
        'service_contracts',
        sa.Column(
            'balance_limit',
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment='Лимит по договору',
        ),
        schema='app',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        'service_contracts',
        'balance_limit',
        schema='app',
    )
    op.drop_column(
        'service_contracts',
        'total_cost',
        schema='app',
    )
    op.drop_column(
        'service_contracts',
        'tariff',
        schema='app',
    )
    op.alter_column(
        'service_contract_visits',
        'invoice_num',
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_comment='Номер накладной',
        schema='app',
    )
    op.alter_column(
        'service_contract_visits',
        'contract_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_comment='ИД договора',
        schema='app',
    )
    op.drop_table(
        'executor_storage_areas',
        schema='app',
    )
    # ### end Alembic commands ###
