"""migration

Revision ID: 0fcba3a5c0b9
Revises: 3b76fc1c2230
Create Date: 2023-08-06 08:39:40.826118+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0fcba3a5c0b9'
down_revision = '3b76fc1c2230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'service_contract_visits',
        sa.Column(
            'truck_number',
            sa.String(length=20),
            nullable=False,
            comment='Номер ТС',
        ),
        schema='app',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        'service_contract_visits',
        'truck_number',
        schema='app',
    )
    # ### end Alembic commands ###
