"""migration

Revision ID: 3b422b276baa
Revises: 756240e13186
Create Date: 2024-06-30 01:57:48.933750+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3b422b276baa'
down_revision = '756240e13186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lots',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('number', sa.Integer(), nullable=False,
                              comment='Номер лота'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_lots')),
                    schema='app',
                    comment='Лот'
                    )
    op.create_table(
        'permission_lots_association',
        sa.Column('permission_id', sa.Integer(), nullable=False,
                  comment='ИД Допуска'),
        sa.Column('lot_id', sa.Integer(), nullable=False,
                  comment='ИД Лота'),
        sa.ForeignKeyConstraint(['lot_id'], ['app.lots.id'],
                                name=op.f(
                                    'fk_permission_lots_association_lot_id_lots')),
        sa.ForeignKeyConstraint(['permission_id'],
                                ['app.permissions.id'], name=op.f(
                'fk_permission_lots_association_permission_id_permissions')),
        schema='app',
    )
    op.alter_column(
        'polygon_details', 'scale_accuracy',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema='app')
    op.add_column(
        'visits', sa.Column('lot_id', sa.Integer(), nullable=True),
        schema='app')
    op.drop_index(
        'visits_checked_out_idx', table_name='visits', schema='app')
    op.create_foreign_key(
        op.f('fk_visits_lot_id_lots'), 'visits', 'lots',
        ['lot_id'], ['id'], source_schema='app',
        referent_schema='app'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_visits_lot_id_lots'), 'visits', schema='app',
                       type_='foreignkey')
    op.create_index('visits_checked_out_idx', 'visits', ['checked_out'],
                    unique=False, schema='app')
    op.drop_column('visits', 'lot_id', schema='app')
    op.alter_column('polygon_details', 'scale_accuracy',
                    existing_type=sa.INTEGER(),
                    nullable=True,
                    schema='app')
    op.drop_table('permission_lots_association', schema='app')
    op.drop_table('lots', schema='app')
    # ### end Alembic commands ###
