"""migration

Revision ID: 5da75bf593b7
Revises: 3b422b276baa
Create Date: 2024-08-18 00:13:20.053233+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5da75bf593b7'
down_revision = '3b422b276baa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waste_type',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=128), nullable=False,
                              comment='Название типа отходов'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_waste_type')),
                    schema='app'
                    )
    op.add_column('contracts',
                  sa.Column('waste_type_id', sa.Integer(), nullable=True),
                  schema='app')
    op.create_foreign_key(op.f('fk_contracts_waste_type_id_waste_type'),
                          'contracts', 'waste_type', ['waste_type_id'], ['id'],
                          source_schema='app', referent_schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_contracts_waste_type_id_waste_type'),
                       'contracts', schema='app', type_='foreignkey')
    op.drop_column('contracts', 'waste_type_id', schema='app')
    op.drop_table('waste_type', schema='app')
    # ### end Alembic commands ###
