"""migration

Revision ID: 756240e13186
Revises: 146064cc58b8
Create Date: 2024-04-12 11:04:11.256349+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '756240e13186'
down_revision = '146064cc58b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polygon_details',
                  sa.Column('scale_accuracy', sa.Integer(), nullable=True),
                  schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polygon_details', 'scale_accuracy', schema='app')
    # ### end Alembic commands ###
